### ISSUE TITLE
Integration with ControlCenter

### ISSUE THREAD

**Issue by dbtucker** [jcustenborder/kafka-connect-simulator#1]
The class name (SimulatorConnector) precludes the connector being visible to the ControlCenter configuration.   The suffix needs to be "SourceConnector".

**Comment by jcustenborder** [comment]
@dbtucker Changed the connector to `com.github.jcustenborder.kafka.connect.simulator.SimulatorSourceConnector` I changed the package as well. I'm going to start publishing my connectors under this namespace to prevent confusion about what is supported by Confluent and by me.

**Comment by dbtucker** [comment]
Thanks, Jeremy !
